data:extend({
  {
    name = "tgne-process-every-tick",
    type = "int-setting",
    setting_type = "runtime-global",
    default_value = 2160,
    minimum_value = 60,
    maximum_value = 216000,
    order = "a",
  },
  {
    name = "tgne-expansion-mean-time",
    type = "int-setting",
    setting_type = "runtime-global",
    default_value = 216000,
    minimum_value = 60,
    maximum_value = 21600000,
    order = "b",
  },
  -- Should be renamed to tnge-distance-spawn-players
  {
    name = "tgne-distance-players",
    type = "double-setting",
    setting_type = "runtime-global",
    default_value = 5,
    minimum_value = 0,
    maximum_value = 10,
    order = "c-a",
  },
  {
    name = "tgne-distance-deconstruct-mature-players",
    type = "double-setting",
    setting_type = "runtime-global",
    default_value = 5,
    minimum_value = 0,
    maximum_value = 10,
    order = "c-b",
  },
  {
    name = "tgne-distance-deconstruct-growing-players",
    type = "double-setting",
    setting_type = "runtime-global",
    default_value = 2,
    minimum_value = 0,
    maximum_value = 10,
    order = "c-c",
  },
  {
    name = "tgne-distance-trees",
    type = "double-setting",
    setting_type = "runtime-global",
    default_value = 0.5,
    minimum_value = 0.5,
    maximum_value = 5,
    order = "d",
  },
  {
    name = "tgne-wind-factor",
    type = "double-setting",
    setting_type = "runtime-global",
    default_value = 100,
    minimum_value = 0,
    maximum_value = 200,
    order = "e",
  },
  {
    name = "tgne-chunk-distance",
    type = "int-setting",
    setting_type = "runtime-global",
    default_value = 3,
    minimum_value = 1,
    maximum_value = 10,
    order = "f",
  },
})
